import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]

[font]
size = 16

[font.normal]
family = "UbuntuMono Nerd Font"

[window]
decorations = "buttonless"
startup_mode = "maximized"

[window.padding]
x = 10
y = 20

