on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: versioning

jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          release-type: simple

